/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import common.MessageDialog;
import dao.StaffDAO;
import models.Staff;
import models.Import;
import models.Distributor;
import dao.DistributorDAO;
import dao.ImportDAO;
import models.ImportDetail;

import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import services.DistributorService;
import services.ImportService;

/**
 *
 * @author gialo
 */
public class ExportFileImport extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudent
     */
    private int teacherId = -200;

    public ExportFileImport() {
        initComponents();
        setLocationRelativeTo(null);
        initializeTable();
    }

    public ExportFileImport(int index) {
        initComponents();
        this.teacherId = index;
        setLocationRelativeTo(null);
        initializeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        importTable = new javax.swing.JTable();
        exportBtn = new javax.swing.JButton();
        exportBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xuất file");

        btn_back.setText("Trở lại trang chủ");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Xuất phiếu nhập hàng");

        importTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        importTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(importTable);

        exportBtn.setBackground(new java.awt.Color(255, 102, 0));
        exportBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exportBtn.setText("Xuất File Excel theo hàng");
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        exportBtn1.setBackground(new java.awt.Color(255, 102, 0));
        exportBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exportBtn1.setText("Xuất toàn bộ File Excel");
        exportBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_back)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(208, 208, 208))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(exportBtn)
                .addGap(81, 81, 81)
                .addComponent(exportBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        dispose();
        Home homeScreen = new Home();
        homeScreen.setLocationRelativeTo(null);
        homeScreen.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void importTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importTableMouseClicked
        try {
            int index = importTable.getSelectedRow();
            if (index == -1) {
                MessageDialog.showInfoDialog(this, "Vui lòng chọn một phiếu nhập", "Thông báo");
                return;
            }

            Import selectedImport = ImportService.getImportByIndex(index);
            String importCode = selectedImport.getCode();


            // Lấy dữ liệu từ ImportDetail
           
        } catch (Exception ex) {
            MessageDialog.showErrorDialog(this, "Có lỗi xảy ra khi lấy thông tin chi tiết phiếu nhập, chi tiết: " + ex.getMessage() + "\n" + ex.toString() + "\n", "Có lỗi xảy ra");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_importTableMouseClicked

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        // TODO add your handling code here:
      try {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn vị trí để xuất file Excel");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Excel Files (*.xlsx)", "xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();

            // Ensure the file has a .xlsx extension
            if (!filePath.toLowerCase().endsWith(".xlsx")) {
                filePath += ".xlsx";
            }

            File file = new File(filePath);

            // Check if the file already exists
            if (file.exists()) {
                MessageDialog.showErrorDialog(this, "Tên file đã tồn tại! Vui lòng chọn tên khác.", "Lỗi");
            } else {
                Workbook workbook = new XSSFWorkbook();

                LocalDate currentDate = LocalDate.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                String formattedDate = currentDate.format(formatter);
                String importTitle = "CHI TIẾT PHIẾU NHẬP TRONG NGÀY " + formattedDate;

                Sheet sheet = workbook.createSheet(importTitle);

                // Create header row
                Row headerRow = sheet.createRow(0);

                CellStyle headerStyle = workbook.createCellStyle();
                headerStyle.setFillForegroundColor(IndexedColors.LIGHT_BLUE.getIndex());
                headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
                headerStyle.setAlignment(HorizontalAlignment.CENTER);

                org.apache.poi.ss.usermodel.Font headerFont = workbook.createFont();
                headerFont.setColor(IndexedColors.WHITE.getIndex());
                headerFont.setBold(true);
                headerStyle.setFont(headerFont);

                String[] headers = {"Mã phiếu nhập", "Tên phiếu nhập", "Mô tả",
                                    "Ngày nhập", "Đối tác", "Mã sản phẩm", "Tên sản phẩm", 
                                    "Nhân viên", "Giá nhập", "Số lượng", "Tổng tiền"};

                for (int i = 0; i < headers.length; i++) {
                    Cell cell = headerRow.createCell(i);
                    cell.setCellValue(headers[i]);
                    cell.setCellStyle(headerStyle);

                    // Auto-size columns
                    sheet.autoSizeColumn(i);
                }

                // Set cell style with borders
                CellStyle cellStyle = workbook.createCellStyle();
                cellStyle.setBorderBottom(BorderStyle.THIN);
                cellStyle.setBottomBorderColor(IndexedColors.BLACK.getIndex());
                cellStyle.setBorderTop(BorderStyle.THIN);
                cellStyle.setTopBorderColor(IndexedColors.BLACK.getIndex());
                cellStyle.setBorderLeft(BorderStyle.THIN);
                cellStyle.setLeftBorderColor(IndexedColors.BLACK.getIndex());
                cellStyle.setBorderRight(BorderStyle.THIN);
                cellStyle.setRightBorderColor(IndexedColors.BLACK.getIndex());

                // Get selected rows from your UI component (e.g., JTable)
                int[] selectedRows = importTable.getSelectedRows();

                List<Import> imports = ImportDAO.readFromFile();
                List<ImportDetail> importDetails = ImportDAO.readImportDetailsFromFile();

                // Create a map to store ImportDetails by importCode
                Map<String, List<ImportDetail>> importDetailsMap = new HashMap<>();
                for (ImportDetail detail : importDetails) {
                    importDetailsMap.computeIfAbsent(detail.getImportCode(), k -> new ArrayList<>()).add(detail);
                }

                int rowNum = 1;
                for (int rowIndex : selectedRows) {
                    Import imp = imports.get(rowIndex);
                    List<ImportDetail> details = importDetailsMap.get(imp.getCode());
                    if (details != null) {
                        for (ImportDetail detail : details) {
                            Row row = sheet.createRow(rowNum++);
                            int colNum = 0;

                            // Fill each cell with data
                            Cell cell = row.createCell(colNum++);
                            cell.setCellValue(imp.getCode());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(imp.getName());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(imp.getDescription());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(imp.getCreateDate());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getDistributorName());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getProductCode());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getProductName());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getStaffName());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getPriceImport());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getQuantity());
                            cell.setCellStyle(cellStyle);

                            // Calculate total price and add to the cell
                            double totalPrice = detail.getPriceImport() * detail.getQuantity();
                            cell = row.createCell(colNum++);
                            cell.setCellValue(totalPrice);
                            cell.setCellStyle(cellStyle);
                        }
                    }
                }

                try (FileOutputStream fileOut = new FileOutputStream(filePath)) {
                    workbook.write(fileOut);
                } catch (Exception exs) {
                    throw exs;
                }

                workbook.close();

                MessageDialog.showInfoDialog(this, "Xuất danh sách thành công! " + "\nNơi lưu: " + filePath, "Thông báo");
            }
        }
    } catch (Exception ex) {
        MessageDialog.showErrorDialog(this, "Có lỗi xảy ra khi xuất Excel. Chi tiết: " + ex.getMessage(), "Lỗi");
        ex.printStackTrace();
    }
    }//GEN-LAST:event_exportBtnActionPerformed

    private void exportBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtn1ActionPerformed
        // TODO add your handling code here:
        try {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn vị trí để xuất file Excel");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Excel Files (*.xlsx)", "xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();

            // Ensure the file has a .xlsx extension
            if (!filePath.toLowerCase().endsWith(".xlsx")) {
                filePath += ".xlsx";
            }

            File file = new File(filePath);

            // Check if the file already exists
            if (file.exists()) {
                MessageDialog.showErrorDialog(this, "Tên file đã tồn tại! Vui lòng chọn tên khác.", "Lỗi");
            } else {
                Workbook workbook = new XSSFWorkbook();

                LocalDate currentDate = LocalDate.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                String formattedDate = currentDate.format(formatter);
                String importTitle = "CHI TIẾT PHIẾU NHẬP TRONG NGÀY " + formattedDate;

                Sheet sheet = workbook.createSheet(importTitle);

                // Create header row
                Row headerRow = sheet.createRow(0);

                CellStyle headerStyle = workbook.createCellStyle();
                headerStyle.setFillForegroundColor(IndexedColors.LIGHT_BLUE.getIndex());
                headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
                headerStyle.setAlignment(HorizontalAlignment.CENTER);

                org.apache.poi.ss.usermodel.Font headerFont = workbook.createFont();
                headerFont.setColor(IndexedColors.WHITE.getIndex());
                headerFont.setBold(true);
                headerStyle.setFont(headerFont);

                String[] headers = {"Mã phiếu nhập", "Tên phiếu nhập", "Mô tả",
                                    "Ngày nhập", "Đối tác", "Mã sản phẩm", "Tên sản phẩm", 
                                    "Nhân viên", "Giá nhập", "Số lượng", "Tổng tiền"};

                for (int i = 0; i < headers.length; i++) {
                    Cell cell = headerRow.createCell(i);
                    cell.setCellValue(headers[i]);
                    cell.setCellStyle(headerStyle);

                    // Auto-size columns
                    sheet.autoSizeColumn(i);
                }

                // Set cell style with borders
                CellStyle cellStyle = workbook.createCellStyle();
                cellStyle.setBorderBottom(BorderStyle.THIN);
                cellStyle.setBottomBorderColor(IndexedColors.BLACK.getIndex());
                cellStyle.setBorderTop(BorderStyle.THIN);
                cellStyle.setTopBorderColor(IndexedColors.BLACK.getIndex());
                cellStyle.setBorderLeft(BorderStyle.THIN);
                cellStyle.setLeftBorderColor(IndexedColors.BLACK.getIndex());
                cellStyle.setBorderRight(BorderStyle.THIN);
                cellStyle.setRightBorderColor(IndexedColors.BLACK.getIndex());

                // Write data to the Excel sheet
                List<Import> imports = ImportDAO.readFromFile();
                List<ImportDetail> importDetails = ImportDAO.readImportDetailsFromFile();

                // Create a map to store ImportDetails by importCode
                Map<String, List<ImportDetail>> importDetailsMap = new HashMap<>();
                for (ImportDetail detail : importDetails) {
                    importDetailsMap.computeIfAbsent(detail.getImportCode(), k -> new ArrayList<>()).add(detail);
                }

                int rowNum = 1;
                for (Import imp : imports) {
                    List<ImportDetail> details = importDetailsMap.get(imp.getCode());
                    if (details != null) {
                        for (ImportDetail detail : details) {
                            Row row = sheet.createRow(rowNum++);
                            int colNum = 0;

                            // Fill each cell with data
                            Cell cell = row.createCell(colNum++);
                            cell.setCellValue(imp.getCode());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(imp.getName());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(imp.getDescription());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(imp.getCreateDate());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getDistributorName());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getProductCode());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getProductName());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getStaffName());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getPriceImport());
                            cell.setCellStyle(cellStyle);

                            cell = row.createCell(colNum++);
                            cell.setCellValue(detail.getQuantity());
                            cell.setCellStyle(cellStyle);

                            // Calculate total price and add to the cell
                            double totalPrice = detail.getPriceImport() * detail.getQuantity();
                            cell = row.createCell(colNum++);
                            cell.setCellValue(totalPrice);
                            cell.setCellStyle(cellStyle);
                        }
                    }
                }

                try (FileOutputStream fileOut = new FileOutputStream(filePath)) {
                    workbook.write(fileOut);
                } catch (Exception exs) {
                    throw exs;
                }

                workbook.close();

                MessageDialog.showInfoDialog(this, "Xuất danh sách thành công! " + "\nNơi lưu: " + filePath, "Thông báo");
            }
        }
    } catch (Exception ex) {
        MessageDialog.showErrorDialog(this, "Có lỗi xảy ra khi xuất Excel. Chi tiết: " + ex.getMessage(), "Lỗi");
        ex.printStackTrace();
    }
    }//GEN-LAST:event_exportBtn1ActionPerformed


    private DefaultTableModel tableModel;

    
    private void loadTableData() {
        try {
            List<Import> import_data = ImportService.getAllImports();
            List<Distributor> dis_data = DistributorService.getAllDistributors();
            tableModel.setRowCount(0);
            if (import_data != null) {
                for (Import impor : import_data) {
                    tableModel.addRow(new Object[]{impor.getCode(),
                        impor.getName(),
                        impor.getDescription(),
                        impor.getCreateDate()});
                }
            }
        } catch (Exception ex) {
            MessageDialog.showErrorDialog(this, "Tải dữ liệu cho bảng có lỗi! Chi tiết: " + ex.getMessage(), "Có lỗi xảy ra");
            ex.printStackTrace();
        }
    }

    private void initializeTable() {
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new String[]{"Mã phiếu nhập", "Tên phiếu nhập", "Mô tả",
            "Ngày nhập"});
        importTable.setModel(tableModel);
        if (teacherId >= 0) {
           
            btn_back.setText("Quay lại trang trước");
        }
        loadTableData();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportFileImport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportFileImport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportFileImport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportFileImport.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ExportFileImport().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton exportBtn;
    private javax.swing.JButton exportBtn1;
    private javax.swing.JTable importTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private double getCellValue(Import tour, int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
